### ISSUE TITLE
druid: update windows instructions

### ISSUE THREAD

**Issue by dndrks** [monome/docs#172]
edit: I can't take this on, as it requires validation and testing through Windows

https://llllllll.co/t/crow-help-general-connectivity-device-qs-ecosystem/25866/113

https://docs.google.com/document/d/11Bnly-JOBh4_mWSyIGmEIpE_YO-6VH179KSHEWTZr2M/edit

supplemental documentation from oootini:

> **Crow becomes unresponsive and won’t respond even after power cycling your case**
> 
> Sometimes a script can crash crow and cause the device to report a “warning: unknown usb device” error. This error persists even after the case is powered down.
> 
> To resolve this error, reflash the device firmware as described in Firmware Update and then run erase_userscript.sh. This removes the broken script that causes crow to crash on startup.
> 
> For windows users, run the following:
> 
> `dfu-util -a 0 -s 0x08020000 -R -D crow.bin -d ,0483:df11`
> then
> `dfu-util -a 0 -s 0x08010000 -R -D blank.bin -d ,0483:df11`
>
> Once you erase the broken script, crow should be back to the default state with the first script loaded.

**Comment by aidanreilly** [comment]
Thanks Dan. I think the main thing that needs communicating is that for an unresponsive crow caused by a broken script, you need to erase the broken user script.

Suggesting something like the below as a new troubleshooting topic in the crow docs that could be added to as issues crop up:

****************************** 

#Troubleshooting common crow issues

Below are issues and potential fixes that you may encounter when using crow.

## Crow becomes unresponsive and won't respond even after power cycling your case

Sometimes a script can crash crow and cause the device to report a "warning: unknown usb device" error. This error persists even after the case is powered down. The error is caused by a script that causes crow to become unresponsive. 

To resolve this error, the crow firmware needs to be erased and the default firmware needs to be reloaded. 

1. Download dfu-utils as described in [Firmware update](update) 
2. Download the latest firmware from [releases](https://github.com/monome/crow/releases).
3. Extract the downloaded zip and run `erase_userscript.sh` and then `flash.sh`. This removes the broken firmware that causes crow to crash on startup and replaces it with the default firmware.

Windows users cannot run .sh scripts. If you are on Windows, run the following from a command prompt opened at the extracted firmware download folder:

    dfu-util -a 0 -s 0x08010000 -R -D blank.bin -d ,0483:df11

then

    dfu-util -a 0 -s 0x08020000 -R -D crow.bin -d ,0483:df11

Once you erase the broken script, crow should be back to the default state with the first script loaded.

**Comment by aidanreilly** [comment]
Also need to update for basic update procedure on windows.

****************
#Windows firmware update procedure

Run the following from a command prompt opened at the extracted firmware download folder:

    dfu-util -a 0 -s 0x08020000 -R -D crow.bin -d ,0483:df11

**Comment by dndrks** [comment]
> Suggesting something like the below as a new troubleshooting topic in the crow docs that could be added to as issues crop up:

this bucket currently lives under `docs/crow/technical`: https://monome.org/docs/crow/technical/#recovering-from-an-unresponsive-state (we have not yet added the windows instructions you've provided)

do you think, rather, https://monome.org/docs/crow/faq/ should have a `troubleshooting` section?

**Comment by aidanreilly** [comment]
I would put it under a new topic at the same level as update, FAQ, etc.  Seems kind of buried in the technical section (i hadn't clocked that the procedure was there actually). And to me, it doesn't fit in a FAQ.

**Comment by aidanreilly** [comment]
These instructions aren’t correct. In my recent experience, the entire force bootload, usb zadig update, dfu erase, and dfu update procedure needs to be run each and every time there is a hard crash. Even then, crow takes a number of power cycles before even being recognized by the zadig exe. 

edit: maybe this will go away with new 1.0.1 firmware. will test.

**Comment by dndrks** [comment]
@aidanreilly , I updated the docs to mirror current best practices on 1.0.1 -- seems like everything is now way more straightforward (including the `windows-erase_userscript.bat`). plz feel free to re-open if I've got any blind spots!!

changed:
https://monome.org/docs/crow/druid/#install-druid-on-windows
https://monome.org/docs/crow/update/#setup-dfu-util
https://monome.org/docs/crow/update/#windows
https://monome.org/docs/crow/technical/#recovering-from-an-unresponsive-state

**Comment by aidanreilly** [comment]
All good! Great effort. 


Aidan

> On 14 Nov 2019, at 20:48, dan derks <notifications@github.com> wrote:
> 

﻿
@aidanreilly , I updated the docs to mirror current best practices on 1.0.1 -- seems like everything is now way more straightforward (including the windows-erase_userscript.bat). plz feel free to re-open if I've got any blind spots!!

changed:
https://monome.org/docs/crow/druid/#install-druid-on-windows
https://monome.org/docs/crow/update/#setup-dfu-util
https://monome.org/docs/crow/update/#windows
https://monome.org/docs/crow/technical/#recovering-from-an-unresponsive-state
