### ISSUE TITLE
"For the best experience with crow, consider its outputs to be control-rate generators"

### ISSUE THREAD

**Issue by zjb-s** [monome/docs#357]
Is this still true, now that Crow has official(?) support for audio-rate oscillation?

(issue credit @postsolarpunk)

**Comment by dndrks** [comment]
hi @zjb-s ! hope all's well :)
crow's support for audio-rate is official! [`oscillate`](https://github.com/monome/docs/blob/8b26a66e93578a0acf9793fd4ed8bd46f53b789a/crow/reference.md?plain=1#L198)
in general, the crow FAQ could use some love. mind if we repurpose this issue to log some change proposals for https://github.com/monome/docs/blob/gh-pages/crow/faq.md ?

**Comment by zjb-s** [comment]
hey hey!

That sounds good to me! Just wanted to post this for him. Thanks :)

**Comment by trentgill** [comment]
wondering if we can close this?

while crow can *output* audiorate signals, it can only collect them at control rate (albeit quite fast at 1.5kHz). more importantly though, crow's API is designed around events & declarative structures. ie the intention is to *describe* an audiorate action, rather than do per-sample manipulation like a live-dsp platform.

either way, if we want to include this note, where should it go?
