### ISSUE TITLE
mixed up bracket in ex. screenshot

### ISSUE THREAD

**Issue by benzweig** [monome/docs#66]
hey there! wasn't sure how to submit a PR for this as it's an image, but on line 26 of https://github.com/monome/docs/blob/master/docs/grid-studies/nodejs/images/grid-studies-nodejs-2.png there appears to be a `[` to the left of `s`, when you want a `{`. only noticed because i wasn't sure why i was getting `key received: 0, 0, $[s}` 😛 

cheers!

**Comment by nightmorph** [comment]
@tehn, if the docs website backend runs jekyll with syntax highlighting (and it looks like it does, per the css), then what about converting the somewhat browser-unfriendly png images to actual code blocks?

then we'd just do:
`
```javascript
all those lines
of code
here
```
`
i'd be willing to make the effort, so long as there's something like code fences to get it to display correctly. otherwise, i'm not sure how we'd regen the screenshot. also, switching to actual inline code might improve searchability.

**Comment by nightmorph** [comment]
thanks to @benzweig for the [patch](https://github.com/monome/docs/pull/67/commits/1d1d0aadd1d8056b564667c047bf3a32826bf784) to fix the actual `grid_studies_2.js` file; now we just need to see what we can do on the website/docs side.

**Comment by tehn** [comment]
agreed, this could be just replaced with a formatted code block as suggested by @nightmorph 

i'm not sure if any syntax highlighters are currently installed but i can look into it

**Comment by tehn** [comment]
fixed https://github.com/monome/docs/commit/474e4f3afded0446132ae3898712e5c61cba3d92
